export const INVENTORY_PAGE_SELECTORS = {
    APP_LOGO: '.app_logo',
    TITLE: '.title',
    OPEN_BURGER_BTN: '#react-burger-menu-btn',
    CLOSE_BURGER_BTN: '#react-burger-cross-btn',
    SIDEBAR_MENU: '.bm-item-list',
    SIDEBAR_MENU_WRAP: '.bm-menu-wrap',
    ALL_ITEM_BTN: '#inventory_sidebar_link',
    ABOUT_BTN: '#about_sidebar_link',
    LOGOUT_BTN: '#logout_sidebar_link',
    RESET_APP_STATE_BTN: '#reset_sidebar_link',
    SORT_FILTER: '.product_sort_container',
    SHOPPING_CART_BTN: '.shopping_cart_link',
    CONTINUE_SHOPPING_BTN: '#continue-shopping',
    ADD_TO_CART_BTN: '#add-to-cart-sauce-labs-backpack',
    REMOVE_BTN: '#remove-sauce-labs-backpack',
    SHOPPING_CART_BADGE: '.shopping_cart_badge',
    INVENTORY_LIST: '.inventory_list',
    INVENTORY_CONTAINER: '[data-test="inventory-item-sauce-labs-backpack-img"]',
};